# Generated by Django 6.0.6 on 2026-07-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_alter_resume_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='color_theme',
            field=models.CharField(choices=[('navy_rose', 'Navy Rose'), ('blue_tech', 'Blue Tech'), ('black_gold', 'Black Gold')], default='navy_rose', max_length=30),
        ),
        migrations.AddField(
            model_name='resume',
            name='template_choice',
            field=models.CharField(choices=[('modern', 'Modern Sidebar'), ('classic', 'Professional Classic'), ('creative', 'Creative Header')], default='modern', max_length=30),
        ),
    ]
