# Generated by Django 6.0.6 on 2026-07-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_resume_color_theme_resume_template_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='color_theme',
            field=models.CharField(choices=[('navy_rose', 'Navy Rose'), ('blue_tech', 'Blue Tech'), ('black_gold', 'Black Gold'), ('emerald_forest', 'Emerald Forest'), ('teal_cyan', 'Teal Cyan'), ('maroon_wine', 'Maroon Wine'), ('graphite_red', 'Graphite Red'), ('indigo_sky', 'Indigo Sky'), ('orange_sunset', 'Orange Sunset'), ('slate_lime', 'Slate Lime'), ('royal_purple', 'Royal Purple'), ('brown_copper', 'Brown Copper')], default='navy_rose', max_length=30),
        ),
    ]
