# Generated by Django 6.0.6 on 2026-07-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_alter_resume_color_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='color_theme',
            field=models.CharField(choices=[('navy_rose', 'Navy Rose'), ('blue_tech', 'Blue Tech'), ('black_gold', 'Black Gold'), ('emerald_forest', 'Emerald Forest'), ('teal_cyan', 'Teal Cyan'), ('maroon_wine', 'Maroon Wine'), ('graphite_red', 'Graphite Red'), ('indigo_sky', 'Indigo Sky'), ('orange_sunset', 'Orange Sunset'), ('slate_lime', 'Slate Lime'), ('royal_purple', 'Royal Purple'), ('brown_copper', 'Brown Copper')], default='navy_rose', max_length=40),
        ),
        migrations.AlterField(
            model_name='resume',
            name='template_choice',
            field=models.CharField(choices=[('modern_sidebar', 'Modern Sidebar'), ('classic_single', 'Classic Single Column'), ('creative_header', 'Creative Header'), ('executive_dark', 'Executive Dark'), ('minimalist_clean', 'Minimalist Clean'), ('tech_grid', 'Tech Grid'), ('elegant_left', 'Elegant Left Panel'), ('academic_formal', 'Academic Formal'), ('compact_ats', 'Compact ATS Friendly'), ('gradient_portfolio', 'Gradient Portfolio')], default='modern_sidebar', max_length=40),
        ),
    ]
